// Package testutil provides testing utilities for the mpv-launcher project.
// It includes FFprobe JSON parsing and fixture-based probers for testing
// without real media files.
package testutil

// FFProbeOutput represents the top-level structure of ffprobe JSON output
// generated by: ffprobe -v quiet -print_format json -show_format -show_streams
type FFProbeOutput struct {
	Streams []FFProbeStream `json:"streams"`
	Format  FFProbeFormat   `json:"format"`
}

// FFProbeStream represents an individual stream (video/audio/subtitle)
type FFProbeStream struct {
	Index          int                `json:"index"`
	CodecName      string             `json:"codec_name"`
	CodecLongName  string             `json:"codec_long_name"`
	CodecType      string             `json:"codec_type"` // "video", "audio", "subtitle"
	CodecTagString string             `json:"codec_tag_string"`
	Profile        string             `json:"profile,omitempty"`
	Width          int                `json:"width,omitempty"`  // Video only
	Height         int                `json:"height,omitempty"` // Video only
	SampleRate     string             `json:"sample_rate,omitempty"`
	Channels       int                `json:"channels,omitempty"`
	ChannelLayout  string             `json:"channel_layout,omitempty"`
	BitsPerSample  int                `json:"bits_per_sample,omitempty"`
	RFrameRate     string             `json:"r_frame_rate,omitempty"`
	AvgFrameRate   string             `json:"avg_frame_rate,omitempty"`
	TimeBase       string             `json:"time_base,omitempty"`
	Duration       string             `json:"duration,omitempty"`
	DurationTs     int64              `json:"duration_ts,omitempty"`
	BitRate        string             `json:"bit_rate,omitempty"`
	NbFrames       string             `json:"nb_frames,omitempty"`
	Disposition    FFProbeDisposition `json:"disposition"`
	Tags           FFProbeTags        `json:"tags,omitempty"`
}

// FFProbeDisposition represents stream disposition flags
type FFProbeDisposition struct {
	Default         int `json:"default"`
	Dub             int `json:"dub"`
	Original        int `json:"original"`
	Comment         int `json:"comment"`
	Lyrics          int `json:"lyrics"`
	Karaoke         int `json:"karaoke"`
	Forced          int `json:"forced"`
	HearingImpaired int `json:"hearing_impaired"`
	VisualImpaired  int `json:"visual_impaired"`
	CleanEffects    int `json:"clean_effects"`
	AttachedPic     int `json:"attached_pic"`
	Captions        int `json:"captions"`
	Descriptions    int `json:"descriptions"`
	Metadata        int `json:"metadata"`
}

// FFProbeTags represents stream metadata tags
type FFProbeTags struct {
	Language    string `json:"language,omitempty"`
	Title       string `json:"title,omitempty"`
	Handler     string `json:"handler_name,omitempty"`
	VendorID    string `json:"vendor_id,omitempty"`
	Encoder     string `json:"encoder,omitempty"`
	CreationTime string `json:"creation_time,omitempty"`
	BPS         string `json:"BPS,omitempty"`
	Duration    string `json:"DURATION,omitempty"`
	NumberOfFrames string `json:"NUMBER_OF_FRAMES,omitempty"`
}

// FFProbeFormat represents container format metadata
type FFProbeFormat struct {
	Filename       string            `json:"filename"`
	NbStreams      int               `json:"nb_streams"`
	NbPrograms     int               `json:"nb_programs"`
	FormatName     string            `json:"format_name"`
	FormatLongName string            `json:"format_long_name"`
	StartTime      string            `json:"start_time,omitempty"`
	Duration       string            `json:"duration,omitempty"`
	Size           string            `json:"size,omitempty"`
	BitRate        string            `json:"bit_rate,omitempty"`
	ProbeScore     int               `json:"probe_score"`
	Tags           map[string]string `json:"tags,omitempty"`
}
